--
-- PostgreSQL database dump
--

\restrict 5g5v3YEJUGPJrnYMKdDWO0fah9szTlJCaNhSAgAxD8Vf7nhXjDFmllSKyhbygJZ

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL,
    trainer_id bigint
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercises (
    id bigint NOT NULL,
    muscle_group character varying(255),
    name character varying(255) NOT NULL
);


ALTER TABLE public.exercises OWNER TO postgres;

--
-- Name: exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plan_exercises (
    id bigint NOT NULL,
    reps_range character varying(255),
    rpe integer,
    sets integer NOT NULL,
    exercise_id bigint,
    workout_day_id bigint
);


ALTER TABLE public.plan_exercises OWNER TO postgres;

--
-- Name: plan_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plan_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_exercises; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session_exercises (
    id bigint NOT NULL,
    notes character varying(255),
    order_index integer,
    exercise_id bigint NOT NULL,
    session_id bigint NOT NULL
);


ALTER TABLE public.session_exercises OWNER TO postgres;

--
-- Name: session_exercises_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session_exercises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_exercises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_sets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.session_sets (
    id bigint NOT NULL,
    reps integer NOT NULL,
    rpe double precision,
    set_number integer NOT NULL,
    weight double precision NOT NULL,
    session_exercise_id bigint NOT NULL
);


ALTER TABLE public.session_sets OWNER TO postgres;

--
-- Name: session_sets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.session_sets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_sets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    body_weight double precision,
    completed boolean NOT NULL,
    end_time timestamp(6) without time zone,
    energy_level integer,
    notes character varying(255),
    sleep_quality integer,
    start_time timestamp(6) without time zone,
    stress_level integer,
    client_id bigint,
    workout_day_id bigint
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trainers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trainers (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255) NOT NULL
);


ALTER TABLE public.trainers OWNER TO postgres;

--
-- Name: trainers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trainers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trainers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_days (
    id bigint NOT NULL,
    day_name character varying(255),
    focus character varying(255),
    workout_plan_id bigint
);


ALTER TABLE public.workout_days OWNER TO postgres;

--
-- Name: workout_days_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_days ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workout_plans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_plans (
    id bigint NOT NULL,
    description character varying(255),
    is_active boolean NOT NULL,
    name character varying(255),
    client_id bigint
);


ALTER TABLE public.workout_plans OWNER TO postgres;

--
-- Name: workout_plans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workout_plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workout_plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (id, email, first_name, last_name, password, trainer_id) FROM stdin;
4	BartekKlient@gmail.com	Bartosz	Testowy	$2a$10$mOSDWxWYOu1vvuXbBf3IUOGH89625AIjX2wXcElpZkRdzSyyIE8.m	\N
3	KacperJanik@gmail.com	Kacper	Janik	$2a$10$ku6Gg1pRowsK2TOILDmi5O68TjiFkF2.Wwr7QBVtHh3UrY2L5vNyq	1
2	RobertKalawski@gmail.com	Robert	Kalawski	$2a$10$inPsdT7GqA2exPugzloStO4dDaScqyNC0iBfQ0QJRuK/acf/Ercvy	2
1	Kevinjeremiasz@gmail.com	Kevin	Jeremiasz	$2a$10$RiMtGe1NsLjeQ6qGKcdtvOAlr6aF70IblPgWaII3J2nfsAdo8L3a2	1
\.


--
-- Data for Name: exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercises (id, muscle_group, name) FROM stdin;
\.


--
-- Data for Name: plan_exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plan_exercises (id, reps_range, rpe, sets, exercise_id, workout_day_id) FROM stdin;
\.


--
-- Data for Name: session_exercises; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session_exercises (id, notes, order_index, exercise_id, session_id) FROM stdin;
\.


--
-- Data for Name: session_sets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.session_sets (id, reps, rpe, set_number, weight, session_exercise_id) FROM stdin;
\.


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sessions (id, body_weight, completed, end_time, energy_level, notes, sleep_quality, start_time, stress_level, client_id, workout_day_id) FROM stdin;
\.


--
-- Data for Name: trainers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trainers (id, email, first_name, last_name, password) FROM stdin;
1	MarekKuzbinski@gmail.com	Marek	Kuzbinski	$2a$10$EhK8fFgYZ5bQ6kq9LVSOLOZI1LhMadRN5M9u1Vix4NBr6gJ1dHIO.
2	DawidTrener@gmail.com	Dawid	Wojciechowski	$2a$10$xdUrLjYiT4fY2dAMgHH9l.pNg7eMZ6ILuiiotXORivoC6TdZV6ffe
3	OskarTrener@gmail.com	Oskar	Trener	$2a$10$fWj/YoHovLBZcSdyvQYBT.7aX13fB4R3Cy/nNUtCo9TrRW7DvSUje
\.


--
-- Data for Name: workout_days; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_days (id, day_name, focus, workout_plan_id) FROM stdin;
\.


--
-- Data for Name: workout_plans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_plans (id, description, is_active, name, client_id) FROM stdin;
2	2 plan dla kevina tym razem opierajacy sie na sile pośladków.	f	Plan trenignowy dla Kevina 2	1
3	2 plan dla kevina tym razem opierajacy sie na sile pośladków.	t	Plan trenignowy dla Kevina 2	1
1	 plan dla kevina tym razem opierajacy sie na sile pośladków.	f	Plan trenignowy dla Kevina 	1
\.


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_id_seq', 4, true);


--
-- Name: exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercises_id_seq', 1, false);


--
-- Name: plan_exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plan_exercises_id_seq', 1, false);


--
-- Name: session_exercises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_exercises_id_seq', 1, false);


--
-- Name: session_sets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.session_sets_id_seq', 1, false);


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sessions_id_seq', 1, false);


--
-- Name: trainers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trainers_id_seq', 3, true);


--
-- Name: workout_days_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_days_id_seq', 1, false);


--
-- Name: workout_plans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workout_plans_id_seq', 3, true);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (id);


--
-- Name: plan_exercises plan_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT plan_exercises_pkey PRIMARY KEY (id);


--
-- Name: session_exercises session_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_exercises
    ADD CONSTRAINT session_exercises_pkey PRIMARY KEY (id);


--
-- Name: session_sets session_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_sets
    ADD CONSTRAINT session_sets_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: trainers trainers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT trainers_pkey PRIMARY KEY (id);


--
-- Name: exercises ukc514au7a6fgk8ahyfws1y84jm; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT ukc514au7a6fgk8ahyfws1y84jm UNIQUE (name);


--
-- Name: trainers ukp760ma5h90yjnu0s0c94jawyb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT ukp760ma5h90yjnu0s0c94jawyb UNIQUE (email);


--
-- Name: clients uksrv16ica2c1csub334bxjjb59; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uksrv16ica2c1csub334bxjjb59 UNIQUE (email);


--
-- Name: workout_days workout_days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_days
    ADD CONSTRAINT workout_days_pkey PRIMARY KEY (id);


--
-- Name: workout_plans workout_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plans
    ADD CONSTRAINT workout_plans_pkey PRIMARY KEY (id);


--
-- Name: plan_exercises fk6sasclitq3wj9ornd6v72uotm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT fk6sasclitq3wj9ornd6v72uotm FOREIGN KEY (exercise_id) REFERENCES public.exercises(id);


--
-- Name: session_exercises fk7n5f7tkelbrxgc1q7ka7oacpo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_exercises
    ADD CONSTRAINT fk7n5f7tkelbrxgc1q7ka7oacpo FOREIGN KEY (exercise_id) REFERENCES public.exercises(id);


--
-- Name: clients fkflbm8oou4u4j1ely2kvnantwc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT fkflbm8oou4u4j1ely2kvnantwc FOREIGN KEY (trainer_id) REFERENCES public.trainers(id);


--
-- Name: session_sets fkgu3ilqnptmlxi07647yld7qhk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_sets
    ADD CONSTRAINT fkgu3ilqnptmlxi07647yld7qhk FOREIGN KEY (session_exercise_id) REFERENCES public.session_exercises(id);


--
-- Name: plan_exercises fkicxqn7deurl719le4bogr6qwr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plan_exercises
    ADD CONSTRAINT fkicxqn7deurl719le4bogr6qwr FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id);


--
-- Name: sessions fkn3wereisme2is39cxv0da3hjw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkn3wereisme2is39cxv0da3hjw FOREIGN KEY (workout_day_id) REFERENCES public.workout_days(id);


--
-- Name: workout_plans fknavqbtppjxedv2br0g2cxl944; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_plans
    ADD CONSTRAINT fknavqbtppjxedv2br0g2cxl944 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: workout_days fknh09x2a6wbmvmjpqo7849vqan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_days
    ADD CONSTRAINT fknh09x2a6wbmvmjpqo7849vqan FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id);


--
-- Name: sessions fkqv5vmph05a8pscq0xg7vlfmj5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkqv5vmph05a8pscq0xg7vlfmj5 FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: session_exercises fksvic8hxpq9hf2vc9mnj3j9vnj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.session_exercises
    ADD CONSTRAINT fksvic8hxpq9hf2vc9mnj3j9vnj FOREIGN KEY (session_id) REFERENCES public.sessions(id);


--
-- PostgreSQL database dump complete
--

\unrestrict 5g5v3YEJUGPJrnYMKdDWO0fah9szTlJCaNhSAgAxD8Vf7nhXjDFmllSKyhbygJZ

